import { MedicineType } from '../types';
export const MEDICINE_TYPES: MedicineType[] = [
    'Tablet',
    'Capsule',
    'Syrup',
    'Suspension',
    'Ampoule',
    'Injection',
    'Vial',
    'Infusion',
    'Powder',
    'Granules',
    'Sachet',
    'Oral Solution',
    'Drop',
    'Oral Drops',
    'Eye Drops',
    'Ear Drops',
    'Nasal Drops',
    'Spray',
    'Nasal Spray',
    'Inhaler',
    'Nebulizer Solution',
    'Ointment',
    'Cream',
    'Gel',
    'Lotion',
    'Foam',
    'Suppository',
    'Patch',
    'Mouthwash',
    'Gargle',
    'Serum',
    'Shampoo',
    'Soap',
    'Equipment',
    'Other'
];
export const MEDICINE_TYPES_PROMPT = MEDICINE_TYPES.join(', ');
